export const LOGIN = 'login' 
export const REGISTER='register'
export const PURCHASEFUND = 'purchase-fund'
export const GETINVOICEDETAILS = 'get-fund-invoice'
export const GETPACKAGES = 'get-packages'
export const CHECKUSEREXIST = 'checkuserexist' 
export const CHECKDOWNLINE = 'check-downline' 
export const SELFTOPUP = 'self-topup' 
export const GETDASHBOARDDETAILS = 'get-user-dashboard' 
export const GETTOPUPBALANCE = 'get-topup-balance' 
export const GETALLCURRENCY = 'getall-currency' 
export const GET_PROJECT_SETTING ='getprojectsettings' 
export const ADMIN_PRODUCTBASE ='getlevelviewtree/productbase'
export const CHECKUSEREXISTED='checkuserexist'
export const SENDOTP='sendOtp-update-user-profile'
export const CASHTOCASH='transfer-topup-to-topup'
export const REG_OTP='sendRegEmailOtp'
export const REG_OTP_VERIFY='verfiy-Reg-EmailOtp'
export const COUNTRY='country'
export const GET_USERID='get-user-id'
export const FORGOT_PASSWORD='reset-passwordlink'
export const FORGOT_PASSWORD_OTP='sendOtp-update-user-profile1'
export const FORGOT_PASSWORD_OTP_CHECK='checkotp2'
export const RESET_PASSWORD='reset-password'
export const CHANGPASSWORD='change-password'
export const GETTOPUPDATA='gettopupdata'
export const GETPROFILEINFO='get-profile-info'
export const GETPROFILEUPDATEINFO='get-profile-update-info'
export const CRYPTOCURRENCYVALIDATION='cryptoCurrency/validation'
export const UPDATEUSER='update-user'
export const UPDATEUSERPARENTID='update-user-parent_id'
export const ADD_TRANSFER_REQUEST='add-transfer-request'
export const GENERATERANDNO='generate-random-no'
export const CHECKOTP='checkotp1'
export const CHECKADDRESS='check_address'
export const CHANGEADDRESS='change-address'
export const UPDATEUSERS='user-update'
export const PURCHASEPACKAGE="purchase-package"
export const FUNDREQUEST='fund-request'
export const GETADDRESS='getaddress'
export const WITHDRAWINCOME='withdraw-income'
export const GETWORKINGWITHDRAWALDEDUCTION='get-working-withdrawal-deduction'
export const VERIFYUSEROTP='verify-user-otp'
export const GETROIBALANCE='get-roi-balance'
export const WITHDRAWROIWALLET='withdraw-roi-wallet'
export const GETWORKINGBALANCE='get-working-balance'
export const TRANSFERFUND='fund-transfer'
export const TRANSFERWORKING='working-to-purchase-self-transfer'
export const TRANSFERROI='roi-to-purchase-self-transfer'
export const TRANSFERCOMP='compound-to-purchase-self-transfer'
export const TRANSFERREWARD='reward-to-purchase-self-transfer'
export const UPDATEUSERDATA='update-user-deatils'








